### ISSUE TITLE
restrict qualifier collision

### ISSUE THREAD

**Issue by revelator** [lhmouse/mcfgthread#19]
Been having trouble for some time with the restrict qualifier, and i suspected a bug with the mingw-w64 abi, but it turns out that mcfgthread redefines the qualifier in its own _crtdef.h which causes this error.
So i changed it to use a guard in case its allready defined which seems to have alleviated the problem.

**Comment by lhmouse** [comment]
`restrict` itself is a keyword in C today but the C++ people don't seem to like it...
GCC provides `__restrict__` as an alternative that is available in both C and C++ and has the same meaning with the `restrict` keyword in C.

I was concerned that `#define`'ing `restrict` and `nullptr` would break some existent code because they aren't reserved identifiers... It turns out to be a bad choice I must acknowledge.

AFAIC the safest solution to this problem is using `__restrict__` only in our code and removing that macro.

**Comment by revelator** [comment]
Will do, im making a build of the gcc-5.4.0 release which im going to 
stick to untill the problem with the hardcoded paths in gcc 6 are resolved.


Den 13-01-2017 kl. 17:48 skrev LH_Mouse:

**Comment by revelator** [comment]
Seems to work so far :) codelite still bitches about restrict but that 
one seems to be simply because its using the qualifier incorrectly as an 
internal enumerator, so cant blame it on the former error.  I made a 
patch to get around that one, but there are other problems with codelite 
which break it though.


Den 13-01-2017 kl. 17:48 skrev LH_Mouse:

**Comment by lhmouse** [comment]
OK for closure?

**Comment by revelator** [comment]
Yep :) and thanks for fixing.


Den 15-01-2017 kl. 09:36 skrev LH_Mouse:
