### ISSUE TITLE
Build instructions do not match

### ISSUE THREAD

**Issue by eldiener** [lhmouse/mcfgthread#26]
The various build shell scripts do not really match what is suggested as the build instructions for your library in the readme.md file. I followed the build shell scripts with my own changes for paths and such, but I think you should synchronize the information so that it is consistent. I realize that this is not a big issue but it confused me when I went to build your library.

**Comment by lhmouse** [comment]
The instructions in `README.md` is a general guide - it merely invokes whatever named `autoreconf`, `make`, `gcc` etc in the current PATH, just like what people usually build things from source on Linux. It is usually not necessary to build in a fresh, empty directory (a notable **counter-example** is GCC).

On the other hand, those `build_*.sh` scripts are provided to build native libraries. They create subdirectories and run `configure` in them so we don't mess up files for x64 and x86.

It is less common to provide scripts for two different native targets. Usually only the `configure` script is shipped with the source code and it is the users that should run it to create `Makefile`s for different targets. In that scenario the instructions in `README.md` is correct and what seems a solution for confusion is to remove `build_*.sh` scripts... But removing them doesn't make things any better, does it?

**Comment by lhmouse** [comment]
If you follow the instructions in `README.md` then you will get a native library that works in your installed environment. There is even no need to read `README.md` (it is _not_ the f**k manual) because everyone that has built some packages from source on Linux knows how to use `automake`. The scripts are only _informative_.

**Comment by lhmouse** [comment]
If you follow the instructions in `README.md` then you will get a native library that works in your installed environment. There is even no need to read `README.md` (it is _not_ the f**king manual) because everyone that has built some packages from source on Linux knows how to use `automake`. The scripts are only _informative_.

**Comment by eldiener** [comment]
You are passing different flags in your readme.md instructions than you are passing in your build scripts for building your library. The end-user may be confused by this ( I was ). That is what concerned me, not the actual sequence of what needs to be done, which is basically the same for both.

**Comment by lhmouse** [comment]
Ah, you are right. Since `README.md` is merely an illustration, it is reasonable to keep commands in it as short as possible. I removed `CFLAGS` and `LDFLAGS` from it.

**Comment by lhmouse** [comment]
Please close this issue if there is no problem. Thanks.

**Comment by lhmouse** [comment]
`README.md` used to talk about building using _mingwbuilds_ toolchains. Since we have switched to _MSYS2_ already those should be updated as well.
