### ISSUE TITLE
Update benchmark results

### ISSUE THREAD

**Issue by CarterLi** [lhmouse/mcfgthread#54]
RT

**Comment by lhmouse** [comment]
The old benchmark was done on a Windows 7 machine. It looks like that the `SRWLOCK` has improved a lot in Windows 10. I would like to optimize it a little before that.

**Comment by lhmouse** [comment]
Done now:  <https://github.com/lhmouse/mcfgthread/blob/master/README.md#benchmarking>

**Comment by lhmouse** [comment]
> Does it mean that MCF is even slower than PTHR? What happened when #THRD > 60?
> 

I suspect [the hash table](https://github.com/lhmouse/mcfgthread/blob/148636846cd9ce8a3d052e156737ce4dbb68b79c/src/fwd.h#L118) has been used up. This is practically not a problem, as seldom do people create 60 threads that are all jammed on a single mutex.

> I saw that MCF lock [uses spinlock](https://github.com/lhmouse/mcfgthread/blob/master/src/mutex.c#L73) to reduce syscalls. For [current benchmark program](https://github.com/lhmouse/mcfgthread/blob/master/mutex_performance.c#L64) there is very high possiblity that the program never enters the NtWaitForKeyedEvent syscall.
> 
> What if there are more things to do when locking so that the program can hit the NtWaitForKeyedEvent syscall?

No, you should run the test yourself; the number of spinning threads is not unlimited. It is possible to 
make threads spin infinitely by replacing `while(--spin >= 0)` with `for(;;)`, however I am sure it will only make your test program run slower, due to increment of bus pressure.

**Comment by CarterLi** [comment]
蛋疼，俩中国人还要用英文交流。。。

> No, you should run the test yourself; the number of spinning threads is not unlimited. It is possible to
> make threads spin infinitely by replacing `while(--spin >= 0)` with `for(;;)`, however I am sure it will only make your test program run slower, due to increment of bus pressure.

我的意思是现在的benchmark基本上是在测你写的spinlock的速度，跟 NtWaitForKeyedEvent 没啥关系。我想知道 NtWaitForKeyedEvent 和 AcquireSRWLockExclusive 的速度比较
