### ISSUE TITLE
About NtWaitForAlertByThreadId and NtAlertThreadByThreadId

### ISSUE THREAD

**Issue by CarterLi** [lhmouse/mcfgthread#56]
我看到 AcquireSRWLockExclusive 和 SleepConditionVariableSRW 都是用 NtWaitForAlertByThreadId

![image](https://user-images.githubusercontent.com/6134068/164074656-7e47cf1a-bd05-49fd-b95d-844142c1439c.png)

https://github.com/processhacker/processhacker/blob/master/phnt/include/ntpsapi.h#L1656

关于SRWLock不支持timed_mutex的问题，NtWaitForAlertByThreadId 本身支持 timeout，只是 AcquireSRWLockExclusive 没开放出来

NtWaitForAlertByThreadId 比 NtWaitForKeyedEvent 参数更少，功能更专用，性能应该会比后者好

包括 rpcs3 也是优先 NtWaitForAlertByThreadId ：https://github.com/valgusk/rpcs3-old-rpcn/blob/f6f12b3b0dfeedc260d44e3be713fcb03c9638eb/rpcs3/util/atomic.cpp#L1192

考虑一下？

**Comment by lhmouse** [comment]
That is a completely different thing. As there is no longer a 'key', it will be necessary to perform some bookkeeping in user mode.

One possible design for reducing bus pressure is [to allocate a structure on the stack and use it to build a wait queue](http://locklessinc.com/articles/locks/). This answers why SRWLOCK doesn't support timeouts: It is not safe to remove nodes from wait queues without global locking, otherwise a thread that attempts to wake up another one which has timed out would reference destroyed objects and cause unpredictable results.

**Comment by CarterLi** [comment]
这个东西我是外行。说的有错不要介意。

> That is a completely different thing. As there is no longer a 'key', it will be necessary to perform some bookkeeping in user mode.

NtWaitForAlertByThreadId，这里的ThreadId不就是这个key？

**Comment by lhmouse** [comment]
No there is no thread ID argument. This function suspends the current thread for the timeout specified by its second argument. See <https://source.winehq.org/source/dlls/ntdll/sync.c#0931> for example.

**Comment by CarterLi** [comment]
> No there is no thread ID argument. This function suspends the current thread for the timeout specified by its second argument. See https://source.winehq.org/source/dlls/ntdll/sync.c#0931 for example.

You can only suspend the current thread, so you don't need to pass the thread ID argument in ( like what `Sleep` does ). It's enough, isn't it?

**Comment by lhmouse** [comment]
Then when a thread attempts to unlock a mutex, how does it know which threads are currently waiting, and which one it should wake up?

**Comment by CarterLi** [comment]
Isn't it stored in the mutex object?

**Comment by CarterLi** [comment]
What is `address` used for? According to [the implementation of wine](https://source.winehq.org/source/dlls/ntdll/unix/sync.c#2414), `address` is completely unsed ( only for tracing ).

**Comment by lhmouse** [comment]
It's unused in Wine. Not sure about Windows.
