### ISSUE TITLE
用mcf线程模型本地或加拿大编译出来的lld (LLVM的链接器)不能用-flto=thin

### ISSUE THREAD

**Issue by trcrsired** [lhmouse/mcfgthread#68]
thin lto不知道为何不能用。换posix的就行。你去修一下吧。

**Comment by lhmouse** [comment]
Did you read <https://github.com/lhmouse/mcfgthread#notes> ?

Or patch the CRT yourself: <https://github.com/lhmouse/mcfgthread/blob/5094283b3165037c7d70a0f93cbc90f5b2b4828e/patches/mingw-w64-10.0.patch#L136>

mcfgthread requires the `fflush()` function be called after user-defined exit callbacks (so it has to be registered before `__main()`), otherwise data in standard output may be truncated upon exit.

**Comment by lhmouse** [comment]
As there was no further feedback I am closing this as WONTFIX.
